Fix audio-config: Add bash to RDEPENDS
The pipewire-user-setup.sh script uses /bin/bash but bash wasn't in
the runtime dependencies, causing a QA error.

Fixes:
ERROR: audio-config-1.0-r0 do_package_qa: QA Issue: /usr/sbin/pipewire-user-setup.sh
contained in package audio-config requires /bin/bash, but no providers found in
RDEPENDS:audio-config